### PR TITLE
Feature/own http server

### PR DESCRIPTION
**Pull request by JanHolger**
This implements an own http server from ground up and abstracts the http server logic from the framework logic so http server implementations are interchangeable. By default the new SimpleHTTPSocketServer will be used but currently there is also a JettyHTTPSocketServer that can be used optionally if something doesn't yet work with the simple implementation. This should removed or moved to a seperate repository so jetty can be removed from the dependencies. The websocket logic is also reimplemented with our own websocket handling instead of the hacky jetty implementation that was previously used. Unfortunately jetty doesn't fully conform to the Java EE standard so it doesn't allow upgrading the connection by yourself and therefore websockets are only working with the simple implementation. I tried several things to hijack the jetty connection but wasn't successful.

### CODE REVIEW

**Review by x7airworker — APPROVED** [review]
Looks good to me.

**Comment by JulianFun123** [comment]
Is multipart form data already implemented?

**Comment by JanHolger** [comment]
> Is multipart form data already implemented?

No, it's not yet implemented for the new server. Jetty is still usable in case you are worried about breaking changes.

**Comment by JanHolger** [comment]
I've changed it back to using jetty as the default until the own implementation is stable enough to be used for any production case.  I've also upgraded to the current jetty version. The upgrade was blocked by the hacky websocket implementation before that has now been removed.

**Comment by JanHolger** [comment]
this also closes #11

**Pull request merged**
